"""Subindo primeira tabela

Revision ID: a99d2b9046f0
Revises: 
Create Date: 2025-08-09 11:39:21.649768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99d2b9046f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('editora', sa.String(length=40), nullable=True),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('ano_publicacao', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livro')
    # ### end Alembic commands ###
